In [2]:
import numpy as np
distance = [55,60,45]
speed= [6,10,7]
dist= np.array(distance)
spd = np.array(speed)
time = dist/spd
print(time)


[9.16666667 6.         6.42857143]


In [5]:
# data type
print("Data type of arry: ", time.dtype)
# no. of dismensions
print("No. of dismensions: ", time.ndim)
# size of each dimension
print("Size of each dimension: ", time.shape)
# total size of array
print("Total size of array: ", time.size)

Data type of arry:  float64
No. of dismensions:  1
Size of each dimension:  (3,)
Total size of array:  3


In [6]:
# Creating arrays with randoms values 
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10,size=6) # One-dimensional array
x2 = np.random.randint(10,size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10,size=(3,4,5)) # Three-dimensional array

print("x1 ndim: ", x1.ndim)
print("x1 shade: ", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shade: ", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shade: ", x3.shape)
print("x3 size: ", x3.size)


x1 ndim:  1
x1 shade:  (6,)
x1 size:  6
x2 ndim:  2
x2 shade:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shade:  (3, 4, 5)
x3 size:  60


In [9]:
f = np.arange(0,20,5)
print("Sequentail array with steps of 5: \n",f)

Sequentail array with steps of 5: 
 [ 0  5 10 15]


In [13]:
print("1-d array: \n", x1)
print("Second element of first array: ",x1[1])
print("Last element of first array: ", x1[-1])
print("Fist element of first array: ",x1[0])

1-d array: 
 [5 0 3 3 7 9]
Second element of first array:  0
Last element of first array:  9
Fist element of first array:  5


In [14]:
print("2-d array: \n", x2)
print("First elements of 2-d array: \n", x2[0,0])
print("3-d Array: \n", x3)
print("First element of 3-d array: \n", x3[0,0,0])


2-d array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
First elements of 2-d array: 
 3
3-d Array: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
First element of 3-d array: 
 8


In [15]:
# Create an array
x = np.arange(10)
print("Our array: ", x)
print("First five elements: ", x[:5])
print("Elements after index 5: ", x[5:])
print("Middle sub-array: ",x[4:7])
print("Every other element: ", x[::2])
print("Every ofther element, starting at index 1: ", x[1::2])
print("Elements in reversed order: ", x[::-1])

Our array:  [0 1 2 3 4 5 6 7 8 9]
First five elements:  [0 1 2 3 4]
Elements after index 5:  [5 6 7 8 9]
Middle sub-array:  [4 5 6]
Every other element:  [0 2 4 6 8]
Every ofther element, starting at index 1:  [1 3 5 7 9]
Elements in reversed order:  [9 8 7 6 5 4 3 2 1 0]


In [16]:
print("2-d array: \n", x2)
print("Two rows, three columns: \n", x2[:2,:3])

2-d array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Two rows, three columns: 
 [[3 5 2]
 [7 6 8]]


In [18]:
# Original array
print("Original 2-d array: \n", x2)
# Creating a 2x2 subarray from the original array
x2_sub = x2[:2, :2]
print("Sub-array: \n", x2_sub)
# Modifying sub-array
x2_sub[0,0] = 88
print("Modified sub array: \n", x2_sub)
# Original array after sub-array changes
print("Original array after changes in sub-array: \n", x2)
print("Making a copy of the original array")
x2_sub_copy = x2[:2,:2].copy()
print("Copy of the orinal array: \n", x2_sub_copy)
# Modifying copied array
x2_sub_copy[0,0] = 42
print("Copied array after changes: \n", x2_sub_copy)
print("Original array: \n",x2)

Original 2-d array: 
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
Sub-array: 
 [[88  5]
 [ 7  6]]
Modified sub array: 
 [[88  5]
 [ 7  6]]
Original array after changes in sub-array: 
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
Making a copy of the original array
Copy of the orinal array: 
 [[88  5]
 [ 7  6]]
Copied array after changes: 
 [[42  5]
 [ 7  6]]
Original array: 
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [21]:
# Creating two sample arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
# Combining both arrays using concatenate
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [26]:
# Creating a sample array
x = np.array([1,2,3])
# Creating a 2-d array
grid = np.array([[9,8,7],
               [6,5,4]])
# Vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [28]:
# Horizontally stack the arrays
y = np.array([[99],
            [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])